FROM eclipse-temurin:17

LABEL mentainer="tonduong2128@gmail.com"

WORKDIR /app

COPY target/StudentsManagement-0.0.1-SNAPSHOT.jar /app/StudentsManagement.jar

ENTRYPOINT ["java", "-jar", "StudentsManagement.jar"]