version: "3.8"

# "spring.datasource.password" : "",
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://192.168.1.15:3306/students_management",
        "spring.datasource.username" : "root",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - E:/Desktop/TKPM/sources/logs:/app/logs
    depends_on:
        - nginx 
    networks:
      - mynetwork
  
  nginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

networks:
  mynetwork: