version: "3.8"

services:
  app:
    image: tonduong/students-management:latest
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://103.97.126.23:3306/scwnbjdt_students_management",
        "spring.datasource.username" : "scwnbjdt_students_management",
        "spring.datasource.password" : "user@123",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - E:/Desktop/TKPM/sources/logs:/app/logs
    depends_on:
        - nginx 
    networks:
      - mynetwork
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    depends_on:
        - nginx 

networks:
  mynetwork: